# Logo
logo_image_source: /images/logo.png
logo_height: 32
logo_width: 272
favicon: /images/favicon.png
# Index Page
index_banner_text: sitename
index_banner_text_secondary: We are the best blog in the world.

# Header
menu:
  Home: /
  Win Gifts: /giveaway/
  Archives: /archives/
  Contact: /contact-us/

posts_widget: '_partial/widget-recent-posts'

sidebar: false

newsletter: true

leaderboard: false

showBio: true

showBanner: true

menu_footer:
  - url: /about-us/
    title: About Us
  - url: /archives/
    title: Archives
  - url: /privacy-policy/
    title: Privacy Policy
  - url: /disclosure/
    title: Disclosure
  - url: /terms-of-use/
    title: Terms of Use
  - url: /contact-us/
    title: Contact Us
  - url: /write-for-us/
    title: Write for Us


# Archive Date Format
archive_date_format: MMM YYYY

# About Widget
about_widget_avatar_url: https://secure.gravatar.com/avatar/244d8e86fdb7534f91c9378011f9abb2?s=96&d=mm&r=g
about_widget_text: ""


# Comments.
comments:
  # Disqus comments
  disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

authors:
  guest:
    name: Guest Author
    avatar: /images/guest.jpg
    about: This is a Guest Post. To submit your post, just contact us.
# Social Media Platforms
social_platforms:
  twitter:
    url: https://twitter.com/
    title: Follow us on Twitter
    svg: <svg xmlns="http://www.w3.org/2000/svg" aria-label="Twitter" role="img" viewBox="0 0 512 512"><rect width="512" height="512" rx="15%" fill="#1da1f3"/><path fill="#fff" d="M437 152a72 72 0 0 1-40 12 72 72 0 0 0 32-40 72 72 0 0 1-45 17 72 72 0 0 0-122 65 200 200 0 0 1-145-74 72 72 0 0 0 22 94 72 72 0 0 1-32-7 72 72 0 0 0 56 69 72 72 0 0 1-32 1 72 72 0 0 0 67 50 200 200 0 0 1-105 29 200 200 0 0 0 309-179 200 200 0 0 0 35-37"/></svg>
  facebook:
    url: https://www.facebook.com/
    svg: <svg xmlns="http://www.w3.org/2000/svg" aria-label="Facebook" role="img" viewBox="0 0 512 512"><rect width="512" height="512" rx="15%" fill="#3b5998"/><path fill="#fff" d="M330 512V322h64l9-74h-73v-47c0-22 6-36 37-36h39V99c-7-1-30-3-57-3-57 0-95 34-95 98v54h-64v74h64v190z"/></svg>
    title: Like us on Facebook
  instagram:
    url: https://www.instagram.com/
    svg: <svg xmlns="http://www.w3.org/2000/svg" aria-label="Instagram" role="img" viewBox="0 0 512 512"><rect width="512" height="512" rx="15%" fill="#d43377"/><g fill="none" stroke="#fff" stroke-width="29"><rect height="296" rx="78" width="296" x="108" y="108"/><circle cx="256" cy="256" r="69"/></g><circle cx="343" cy="169" fill="#fff" r="19"/></svg>
    title: Follow us on Instagram
  linkedin:
    url: https://www.linkedin.com/company/
    title: Follow us on LinkedIn
    svg:  <svg xmlns="http://www.w3.org/2000/svg" aria-label="LinkedIn" role="img" viewBox="0 0 512 512" fill="#fff"><rect width="512" height="512" rx="15%" fill="#0077b5"/><circle cx="142" cy="138" r="37"/><path stroke="#fff" stroke-width="66" d="M244 194v198M142 194v198"/><path d="M276 282c0-20 13-40 36-40 24 0 33 18 33 45v105h66V279c0-61-32-89-76-89-34 0-51 19-59 32"/></svg>
  pinterest:
    url: https://www.pinterest.com/
    title: Follow us Pinterest
    svg: <svg xmlns="http://www.w3.org/2000/svg" aria-label="Pinterest" role="img" viewBox="0 0 512 512"><rect width="512" height="512" rx="15%" fill="#bd081b"/><path d="m265 65c-104 0-157 75-157 138 0 37 14 71 45 83 5 2 10 0 12-5l3-18c2-6 1-7-2-12-9-11-15-24-15-43 0-56 41-106 108-106 60 0 92 37 92 85 0 64-28 116-70 116-23 0-40-18-34-42 6-27 19-57 19-77 0-18-9-34-30-34-24 0-42 25-42 58 0 20 7 34 7 34l-29 120a249 249 0 0 0 2 86l3-1c2-3 31-37 40-72l16-61c7 15 29 28 53 28 71 0 119-64 119-151 0-66-56-126-140-126z" fill="#fff"/></svg>
  googleplus:
    url: https://plus.google.com/b/
    svg: <svg xmlns="http://www.w3.org/2000/svg" aria-label="Google+" role="img" viewBox="0 0 512 512"><rect width="512" height="512" rx="15%" fill="#dc4639"/><path fill="#fff" d="M191 234v47h72c-2 19-21 55-72 55-43 0-78-36-78-80s33-80 76-80c25 0 42 10 51 19l35-33a125 125 0 0 0-211 94c0 70 57 127 127 127 74 0 122-53 122-125l-2-24"/><path stroke="#fff" stroke-width="29" d="M404 192v118m59-59H345"/></svg>
    title: Follow us on Google+
  email:
    url: mailto:contact@gmail.com
    svg: <svg xmlns="http://www.w3.org/2000/svg" aria-label="Mail" role="img" viewBox="0 0 512 512"><rect width="512" height="512" rx="15%" fill="#328cff"/><path d="m250 186c-46 0-69 35-69 74 0 44 29 72 68 72 43 0 73-32 73-75 0-44-34-71-72-71zm-1-37c30 0 57 13 77 33 0-22 35-22 35 1v150c-1 10 10 16 16 9 25-25 54-128-14-187-64-56-149-47-195-15-48 33-79 107-49 175 33 76 126 99 182 76 28-12 41 26 12 39-45 19-168 17-225-82-38-68-36-185 67-248 78-46 182-33 244 32 66 69 62 197-2 246-28 23-71 1-71-32v-11c-20 20-47 32-77 32-57 0-108-51-108-108 0-58 51-110 108-110" fill="#fff"/></svg>
    title: Email us
  rss:
    url: /atom.xml
    svg: <svg xmlns="http://www.w3.org/2000/svg" aria-label="RSS" role="img" viewBox="0 0 512 512"><rect width="512" height="512" rx="15%" fill="#f80"/><circle cx="145" cy="367" r="35" fill="#fff"/><path fill="none" stroke="#fff" stroke-width="60" d="M109 241c89 0 162 73 162 162M109 127c152 0 276 124 276 276"/></svg>
    title: Subscribe to RSS Feed
  tumblr:
    url: https://www.tumblr.com
    svg: <svg xmlns="http://www.w3.org/2000/svg" aria-label="Tumblr" role="img" viewBox="0 0 512 512"><rect width="512" height="512" rx="15%" fill="#35465c"/><path fill="#fff" d="M361 415c-12 13-40 21-65 21h-3c-85 0-103-61-103-98V236h-35c-3 0-6-3-6-8v-47c0-6 3-10 7-11 44-17 57-54 60-83 0-8 5-11 12-11h50c4 0 6 3 6 6v82h58c5 0 8 3 8 8v56c0 4-3 7-8 7h-58v94c0 24 16 30 25 30 10 0 18-2 23-4 8-4 13 1 14 4l15 45c2 4 3 8 0 11z"/></svg>
    title: Follow us on Tumblr
  youtube:
    url: https://www.youtube.com
    svg: <svg xmlns="http://www.w3.org/2000/svg" aria-label="YouTube" role="img" viewBox="0 0 512 512" fill="#ed1d24"><rect width="512" height="512" rx="15%"/><path d="m427 169c-4-15-17-27-32-31-34-9-239-10-278 0-15 4-28 16-32 31-9 38-10 135 0 174 4 15 17 27 32 31 36 10 241 10 278 0 15-4 28-16 32-31 9-36 9-137 0-174" fill="#fff"/><path d="m220 203v106l93-53"/></svg>
    title: Watch our Videos on Youtube
  newsletter:
    url: https://mailchimp.com
    svg: <svg xmlns="http://www.w3.org/2000/svg" aria-label="Email" role="img" viewBox="0 0 512 512"><rect width="512" height="512" rx="15%" fill="teal"/><rect width="356" height="256" x="78" y="128" fill="#fff" rx="8%"/><path fill="none" stroke="teal" stroke-width="20" d="M434 128L269 292c-7 8-19 8-26 0L78 128m0 256l129-128m227 128L305 256"/></svg>
    title: Join our Newsletter

# Footer about
footer_about: "Site Name"

banner: /images/banner.jpg

yandexId: 12345678

mailchimp:
  user:
  u:
  id:

twitter_handle: 'travel'

convertfox:
  enable: false
  appId: ''

fb:
  enable: false
  pixelid: 1854880834750809

adsense:
  enable: false
  id: 
  pageAds: true

amazon:
  ads:
    - ''
  popover:
      enable: false
      linkid: ''

enableSubtitle: false

marketing:
  enable: false
  image: ''
  link: ''
  title: ''
  subtitle: ''
carousel:
  enable: false
  items:
    - url: ''
      image: ''

homePageText: ''

affiliteText: 'We are a participant in the Amazon Services LLC Associates Program, an affiliate advertising
            program designed to provide a means for sites to earn advertising fees by advertising and linking
            to Amazon.com, Amazon.co.uk or Amazon.ca.'